#!/usr/bin/env python3

import argparse
import glob
import re

CITE_RE = re.compile(r"\\cite(?:\[[^\]]+\])?\{([^}]+)\}")

def extract_cited_keys(tex_files):
    keys = set()
    for path in tex_files:
        with open(path) as f:
            content = f.read()
        for match in CITE_RE.finditer(content):
            keys.add(match.group(1))
    return keys

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--glob", default="src/*/*.tex", help="Glob pattern for .tex files to scan for \\cite{...}")
    parser.add_argument("--macro", default="citationcount", help="Name of the LaTeX macro to define")
    args = parser.parse_args()

    tex_files = sorted(glob.glob(args.glob))
    assert tex_files, f"No files matched glob {args.glob!r}; check the pattern and working directory."
    keys = extract_cited_keys(tex_files)
    assert keys, f"Found {len(tex_files)} files but no \\cite{{...}} invocations at all; something is wrong."

    print(f"% Auto-generated by tools/count_citations.py -- do not edit by hand.")
    print(f"\\newcommand{{\\{args.macro}}}{{{len(keys)}}}")
